inherit_from: configs/Replica/replica.yaml
mapping:
  bound:  [[-3,3],[-3,3],[-0.5,1]] #VICON ROOM
  marching_cubes_bound:  [[-3,3],[-3,3],[-0.5,1]]
  keyframe_every: 1
  map_every: 1
  filter_depth: True
  iters: 50 # global BA iters, defaul 10
  first_iters: 200 # default 200 
  

mesh: 
  render_color: True
  vis: 600
  voxel_eval: 0.01
  voxel_final: 0.01
  render_color: True


cam: 
  H: 360
  W: 640

  # miriel 
  fx: 500.20556666666664 
  fy: 500.1016433333333 
  cx: 324.2802733333333 
  cy: 186.87980166666665

  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 10. # this is for calculating sdf loss. in m
  max_depth: 10000. # where I cut my depth pixel value


data:
  datadir: data/Replica/single_oogway_sep11_scene1
  trainskip: 1
  output: output/Replica/sep11_scene1
  exp_name: RAMEN
  load_path: fixed_decoder.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.95], [0,2,0.95], [1,2,0.95] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: True
  fix_decoder: True
  #alpha: 0.15 # DSGD
  alpha: 0.02 # DSGT

