inherit_from: configs/Replica/replica.yaml
mapping:
  # bound:  [[-3,3],[-3,3],[-1,1]] #VICON ROOM
  # marching_cubes_bound:  [[-3,3],[-3,3],[-1,1]]
  #flip Y-Z
  bound:  [[-3,3],[-0.5,1], [-3,3]] #VICON ROOM
  marching_cubes_bound:  [[-3,3],[-0.5,1], [-3,3]]
  keyframe_every: 1
  map_every: 1
  filter_depth: True
  iters: 10 # global BA iters, defaul 10
  first_iters: 200 # default 200 
  

mesh: 
  render_color: True
  vis: 25
  voxel_eval: 0.02
  voxel_final: 0.02
  render_color: True

grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size: 16
  voxel_color: 0.08 # default 0.08
  voxel_sdf: 0.02 # default 0.02
  oneGrid: True


cam: 
  #H: 360
  #W: 640
  
  #VGGT
  H: 294  
  W: 518

  # miriel 
  # fx: 500.20556666666664 
  # fy: 500.1016433333333 
  # cx: 324.2802733333333 
  # cy: 186.87980166666665

  # from VGGT
  fx: 499.7260437011719
  fy: 497.7563171386719
  cx: 259.0
  cy: 147.0000

  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 10. 

data:
  datadir: data/Replica/vggt_long_replica
  trainskip: 1
  output: output/Replica/vggt_long_replica
  exp_name: vicon_pose
  load_path: fixed_decoder.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 1
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.5], [0,2,0.5], [1,2,0.5] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'CADMM'
  rho: 0.0001
  track_uncertainty: True
  fix_decoder: False
  #alpha: 0.15 # DSGD
  alpha: 0.02 # DSGT

